apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name2 }}
  labels:
    app: nginx2
spec:
  replicas: {{ .Values.deployment.replicas2 }}
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: {{ .Values.deployment.image2.repository }}/{{ .Values.deployment.image2.name }}:{{ .Values.deployment.image2.tag }}
        ports:
        - containerPort: {{ .Values.deployment.port2 }}

