apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name1 }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.deployment.replicas1 }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.deployment.image1.repository }}/{{ .Values.deployment.image1.name }}:{{ .Values.deployment.image1.tag }}
        ports:
        - containerPort: {{ .Values.deployment.port1 }}

