apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path1 }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name1 }}
            port:
              number: {{ .Values.service.port1 }}
      - path: {{ .Values.ingress.path2 }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name2 }}
            port:
              number: {{ .Values.service.port2 }}          
           
