apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name2 }}
spec:
  type: {{ .Values.service.type2 }}
  selector:
    app: nginx2
  ports:
    - protocol: TCP
      port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.service.targetPort2 }}
      nodePort: {{ .Values.service.nodePort2 }}

