apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name1 }}
spec:
  type: {{ .Values.service.type1 }}
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.service.port1 }}
      targetPort: {{ .Values.service.targetPort1 }}
      nodePort: {{ .Values.service.nodePort1 }}

